### ISSUE TITLE
Bug Found: Tag Autocomplete Plugin

### ISSUE THREAD

**Issue by Chucklahoma** [shivams/zim-tag-autocompletion#3]
Bug report attached.
[ZimWikiError_FoundWhenAutocompleteWasInitiated.txt](https://github.com/shivams/zim-tag-autocompletion/files/7232301/ZimWikiError_FoundWhenAutocompleteWasInitiated.txt)

**Comment by fmos** [comment]
Judging from the attached strack trace, this is a duplicate of #2 and can be closed.
